name: Create new release
on:
  push:
    branches:
      - '!*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version  (ie 1.2.0)'
        required: true

jobs:
  createrelease:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create tag name
        run: |
          echo "REL_TAG=$(TZ=':Europe/Athens' date '+%Y.%-m.%-d')" >> $GITHUB_ENV
          echo "BODY_TS=$(TZ=':Europe/Athens' date '+%d-%m-%Y %H:%M:%S')" >> $GITHUB_ENV
      
      - name: Compress xml files
        run: |
          gzip -rk generated_xmltv

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.versionName }}
          release_name: Release ${{ github.event.inputs.versionName }}
          body: |
            Auto generated xmltv files for ${{ env.BODY_TS }}
            - Channel data for Nationwide channels and Attica: `grxmltv_nat_el.xml`
            - Channels from all regions available at Digea.gr and all available national channels from Ert.gr: `xmltv_GREECE_el.xml`
          draft: false
          prerelease: false
      
      - name: Upload Release Assets
        id: upload-release-assets
        uses: shogo82148/actions-upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./generated_xmltv/*
          overwrite: true