name: ci-Tests
 
on:
 push:
   branches:
     - ci-workflows

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out the repo under $GITHUB_WORKSPACE
        uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Push a commit using the built-in token
        run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated on $(date '+%d-%m-%Y %H:%M:%S')"
          git push